import json
import os
from pathlib import Path
from urllib.parse import urljoin

import requests
from flask import Flask, jsonify, request
from openai import OpenAI


JAC_URL = "https://jacresults.com/"
OWNER_NAME = "Priyanshu Raj"
INSTAGRAM_URL = "https://instagram.com/priyanshuxraj"
STATE_FILE = Path("alert_state.json")

AI_DISCLAIMER = (
    "Disclaimer: This response may be generated by an AI assistant using official JAC website data when available. "
    "It can still be inaccurate because of website changes, network issues, or parsing mistakes. "
    "Please verify the final result or marksheet on the official JAC portal."
)

SYSTEM_PROMPT = f"""
You are a Telegram bot for Jharkhand Academic Council Class 12 result help.
Bot owner: {OWNER_NAME}
Official result website: {JAC_URL}

Your style:
- Sound warm, natural, helpful, and brief.
- Use simple language.
- Answer like a real assistant, not a rigid command bot.
- Never invent official result status or result data.
- If the official result is not live, say so clearly.
- If the user asks who made the bot, mention {OWNER_NAME}.
- If the user asks how to use the bot, explain clearly.
- If the user wants to check their result and the official result is live, ask for missing fields step by step.
- Required result fields are: roll code, roll number, stream.
- Supported streams: science, commerce, arts.
- Supported preferred formats: html, pdf, or text fallback.
- If direct fetch is not available yet, say that honestly and offer the official site.
- Keep replies concise and useful.
"""

app = Flask(__name__)
CHAT_STATES = {}
CHAT_RESPONSE_IDS = {}


def get_env(name: str, default: str | None = None) -> str:
    value = os.environ.get(name, "").strip()
    if value:
        return value
    if default is not None:
        return default
    raise RuntimeError(f"Missing environment variable: {name}")


def normalize_text(text: str) -> str:
    return " ".join(text.lower().strip().split())


def load_state() -> dict:
    if not STATE_FILE.exists():
        return {"already_alerted": False}
    try:
        return json.loads(STATE_FILE.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"already_alerted": False}


def save_state(state: dict) -> None:
    STATE_FILE.write_text(json.dumps(state), encoding="utf-8")


def fetch_jac_homepage() -> str:
    response = requests.get(
        JAC_URL,
        headers={"User-Agent": "JACTelegramAIBot/1.0"},
        timeout=30,
    )
    response.raise_for_status()
    return response.text


def class_12_live() -> bool:
    html = fetch_jac_homepage().lower()
    markers = (
        "class xii",
        "class 12",
        "annual intermediate examination - 2026",
        "intermediate examination - 2026",
    )
    return any(marker in html for marker in markers)


def result_entry_live() -> bool:
    html = fetch_jac_homepage().lower()
    return (
        "enter-class-xii-2026" in html
        or "enter-class-xii-arts-2026" in html
        or "results of annual intermediate examination - 2026" in html
    )


def homepage_summary() -> str:
    html = " ".join(fetch_jac_homepage().split())
    compact = html[:1800]
    return compact


def send_telegram_message(chat_id: int, text: str, include_owner_buttons: bool = False) -> None:
    token = get_env("TELEGRAM_BOT_TOKEN")
    api_url = urljoin(f"https://api.telegram.org/bot{token}/", "sendMessage")
    payload = {
        "chat_id": str(chat_id),
        "text": text,
    }
    if include_owner_buttons:
        payload["reply_markup"] = json.dumps(
            {
                "inline_keyboard": [
                    [{"text": f"Owner: {OWNER_NAME}", "url": INSTAGRAM_URL}],
                    [{"text": "Instagram: @priyanshuxraj", "url": INSTAGRAM_URL}],
                ]
            }
        )
    response = requests.post(api_url, data=payload, timeout=30)
    response.raise_for_status()


def command_guide() -> str:
    return (
        f"Hello! I am {OWNER_NAME}'s JAC Class 12 result bot.\n\n"
        "Useful commands:\n"
        "/start - Show welcome message and commands\n"
        "help - Show how to use this bot\n"
        "result live or not - Check whether the official JAC Class 12 result is live\n"
        "check my result - Start result-check help\n"
        "who created this bot - Show creator details\n\n"
        "Result flow:\n"
        "1. Send: check my result\n"
        "2. Send your roll code\n"
        "3. Send your roll number\n"
        "4. Send your stream: science, commerce, or arts\n"
        "5. Choose format: html, pdf, or text fallback\n\n"
        f"{AI_DISCLAIMER}"
    )


def openai_client() -> OpenAI:
    return OpenAI(api_key=get_env("OPENAI_API_KEY"))


def ask_openai(chat_id: int, user_text: str, context_block: str) -> str:
    client = openai_client()
    model = get_env("OPENAI_MODEL", "gpt-5.2")
    previous_response_id = CHAT_RESPONSE_IDS.get(chat_id)

    input_text = (
        f"Live context for this reply:\n{context_block}\n\n"
        f"User message:\n{user_text}\n\n"
        f"Always stay grounded in the live context above.\n"
        f"Add this disclaimer only when discussing actual result/result-check reliability:\n{AI_DISCLAIMER}"
    )

    kwargs = {
        "model": model,
        "instructions": SYSTEM_PROMPT,
        "input": input_text,
    }
    if previous_response_id:
        kwargs["previous_response_id"] = previous_response_id

    response = client.responses.create(**kwargs)
    CHAT_RESPONSE_IDS[chat_id] = response.id
    return response.output_text.strip()


def creator_requested(text: str) -> bool:
    lowered = normalize_text(text)
    return any(
        phrase in lowered
        for phrase in (
            "who created this bot",
            "who made this bot",
            "creator",
            "owner",
            "developer",
        )
    )


def start_lookup_if_possible(chat_id: int) -> tuple[str, bool]:
    if not class_12_live():
        context = (
            f"official_result_live=false\n"
            f"official_result_entry_live={result_entry_live()}\n"
            f"official_site={JAC_URL}\n"
            "User asked to check their result, but the official Class 12 result is not live yet."
        )
        return ask_openai(chat_id, "check my result", context), False

    CHAT_STATES[chat_id] = {"step": "await_roll_code"}
    context = (
        f"official_result_live=true\n"
        f"official_result_entry_live={result_entry_live()}\n"
        "Start the result-check flow and ask only for roll code now."
    )
    return ask_openai(chat_id, "check my result", context), False


def handle_lookup_flow(chat_id: int, message_text: str) -> str | None:
    state = CHAT_STATES.get(chat_id)
    if not state:
        return None

    text = message_text.strip()
    step = state["step"]

    if step == "await_roll_code":
        state["roll_code"] = text
        state["step"] = "await_roll_number"
        context = (
            "official_result_live=true\n"
            "lookup_step=await_roll_number\n"
            f"roll_code={state['roll_code']}\n"
            "Ask only for roll number."
        )
        return ask_openai(chat_id, text, context)

    if step == "await_roll_number":
        state["roll_number"] = text
        state["step"] = "await_stream"
        context = (
            "official_result_live=true\n"
            "lookup_step=await_stream\n"
            f"roll_code={state['roll_code']}\n"
            f"roll_number={state['roll_number']}\n"
            "Ask only for stream. Allowed values: science, commerce, arts."
        )
        return ask_openai(chat_id, text, context)

    if step == "await_stream":
        stream = normalize_text(text)
        if stream not in {"science", "commerce", "arts"}:
            context = (
                "official_result_live=true\n"
                "lookup_step=await_stream\n"
                "User gave invalid stream."
            )
            return ask_openai(chat_id, text, context)
        state["stream"] = stream
        state["step"] = "await_format"
        context = (
            "official_result_live=true\n"
            "lookup_step=await_format\n"
            f"roll_code={state['roll_code']}\n"
            f"roll_number={state['roll_number']}\n"
            f"stream={state['stream']}\n"
            "Ask only for preferred format. Allowed values: html, pdf, text."
        )
        return ask_openai(chat_id, text, context)

    if step == "await_format":
        format_choice = normalize_text(text)
        if format_choice not in {"html", "pdf", "text"}:
            context = (
                "official_result_live=true\n"
                "lookup_step=await_format\n"
                "User gave invalid format."
            )
            return ask_openai(chat_id, text, context)

        state["format"] = format_choice
        CHAT_STATES.pop(chat_id, None)
        context = (
            f"official_result_live={class_12_live()}\n"
            f"official_result_entry_live={result_entry_live()}\n"
            f"roll_code={state['roll_code']}\n"
            f"roll_number={state['roll_number']}\n"
            f"stream={state['stream']}\n"
            f"preferred_format={state['format']}\n"
            "The real 2026 direct fetch flow is not implemented yet. "
            "Be honest: say the details are recorded, direct official fetch is not wired yet, "
            "and fallback text help is available. Include the reliability disclaimer."
        )
        return ask_openai(chat_id, text, context)

    CHAT_STATES.pop(chat_id, None)
    return None


def build_context_for_general_message(text: str) -> str:
    normalized = normalize_text(text)
    live = class_12_live()
    entry_live = result_entry_live()
    summary = homepage_summary()
    return (
        f"official_result_live={live}\n"
        f"official_result_entry_live={entry_live}\n"
        f"official_site={JAC_URL}\n"
        f"creator_name={OWNER_NAME}\n"
        f"homepage_summary={summary}\n"
        f"user_message_normalized={normalized}"
    )


def run_alert_check() -> dict:
    state = load_state()
    live = class_12_live()

    if live and not state.get("already_alerted", False):
        chat_id = int(get_env("TELEGRAM_CHAT_ID"))
        send_telegram_message(
            chat_id,
            f"JAC Class 12 result appears to be live now on the official site: {JAC_URL}",
        )
        state["already_alerted"] = True
        save_state(state)
        return {"ok": True, "alert_sent": True, "live": True}

    if not live and state.get("already_alerted", False):
        state["already_alerted"] = False
        save_state(state)

    return {"ok": True, "alert_sent": False, "live": live}


@app.get("/")
def healthcheck():
    return jsonify({"ok": True, "service": "jac-telegram-bot"})


@app.post("/telegram")
def telegram_webhook():
    update = request.get_json(silent=True) or {}
    message = update.get("message") or {}
    chat = message.get("chat") or {}
    text = message.get("text")
    chat_id = chat.get("id")

    if not text or not chat_id:
        return jsonify({"ok": True})

    normalized = normalize_text(text)
    include_owner_buttons = creator_requested(text)

    try:
        lookup_reply = handle_lookup_flow(chat_id, text)
        if lookup_reply is not None:
            reply = lookup_reply
        elif normalized in {"/start", "start", "help", "/help", "commands", "menu"}:
            reply = command_guide()
        elif any(
            phrase in normalized
            for phrase in (
                "check result",
                "my result",
                "check my result",
                "result check",
                "check my marks",
                "get my result",
            )
        ):
            reply, include_owner_buttons = start_lookup_if_possible(chat_id)
        else:
            reply = ask_openai(chat_id, text, build_context_for_general_message(text))
    except Exception as exc:
        print(f"Telegram AI reply failed: {type(exc).__name__}: {exc}", flush=True)
        if normalized in {"help", "/help", "/start", "start"}:
            reply = command_guide()
        elif "result" in normalized or "live" in normalized or "jac" in normalized:
            reply = (
                f"I could not use the AI reply right now, but I checked the official site.\n"
                f"{'The result appears live.' if class_12_live() else 'The result is not live yet.'}\n"
                f"Official site: {JAC_URL}"
            )
        else:
            reply = (
                "I could not use the AI reply right now. Please try again in a moment, "
                "or ask: result live or not"
            )

    send_telegram_message(chat_id, reply, include_owner_buttons=include_owner_buttons)
    return jsonify({"ok": True})


@app.get("/check")
def scheduled_check():
    secret = request.args.get("key", "")
    expected = get_env("CRON_SECRET")
    if secret != expected:
        return jsonify({"ok": False, "error": "unauthorized"}), 403
    return jsonify(run_alert_check())


if __name__ == "__main__":
    port = int(os.environ.get("PORT", "10000"))
    app.run(host="0.0.0.0", port=port)
