import json
import os
from datetime import datetime
from pathlib import Path
from urllib.parse import urljoin

import requests
from flask import Flask, jsonify, request
from openai import OpenAI


NEET_URL = "https://exams.nta.ac.in/NEET/"
OWNER_NAME = "Priyanshu Raj"
INSTAGRAM_URL = "https://instagram.com/priyanshuxraj"
STATE_FILE = Path("alert_state.json")

AI_DISCLAIMER = (
    "Disclaimer: This response may be generated by an AI assistant using official NTA NEET website data when available. "
    "It can still be inaccurate because of website changes, network issues, or parsing mistakes. "
    "Please verify the final result or score card on the official NTA NEET portal."
)

SYSTEM_PROMPT = f"""
You are a Telegram bot for NEET result help.
Bot owner: {OWNER_NAME}
Official result website: {NEET_URL}

Your style:
- Sound warm, natural, helpful, and brief.
- Use simple language.
- Answer like a real assistant, not a rigid command bot.
- Never invent official result status or result data.
- If the official result is not live, say so clearly.
- If the user asks who made the bot, mention {OWNER_NAME}.
- If the user asks how to use the bot, explain clearly.
- This bot is mainly for NEET result live/not-live checking.
- If the user asks to check their exact result, be honest that the official candidate login flow is not wired into this bot yet unless explicit live login details are provided in context.
- Keep replies concise and useful.
"""

app = Flask(__name__)
CHAT_RESPONSE_IDS = {}


def get_env(name: str, default: str | None = None) -> str:
    value = os.environ.get(name, "").strip()
    if value:
        return value
    if default is not None:
        return default
    raise RuntimeError(f"Missing environment variable: {name}")


def exam_year() -> str:
    return os.environ.get("RESULT_YEAR", str(datetime.now().year)).strip()


def normalize_text(text: str) -> str:
    return " ".join(text.lower().strip().split())


def load_state() -> dict:
    if not STATE_FILE.exists():
        return {"already_alerted": False}
    try:
        return json.loads(STATE_FILE.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"already_alerted": False}


def save_state(state: dict) -> None:
    STATE_FILE.write_text(json.dumps(state), encoding="utf-8")


def fetch_neet_homepage() -> str:
    response = requests.get(
        NEET_URL,
        headers={"User-Agent": "NEETTelegramAIBot/1.0"},
        timeout=30,
    )
    response.raise_for_status()
    return response.text


def neet_result_live() -> bool:
    year = exam_year()
    html = fetch_neet_homepage().lower()
    markers = (
        f"neet(ug) {year} - result",
        f"neet (ug) {year} - result",
        f"neet(ug)-{year} - result",
        f"result of neet (ug) - {year}",
        f"score card({year}",
        f"score card ({year}",
    )
    return any(marker in html for marker in markers)


def result_entry_live() -> bool:
    year = exam_year()
    html = fetch_neet_homepage().lower()
    return year in html and any(
        marker in html
        for marker in (
            "score card",
            "download score card",
            "candidate activity",
            "application no",
            "candidate login",
            "view result",
        )
    )


def homepage_summary() -> str:
    html = " ".join(fetch_neet_homepage().split())
    return html[:1800]


def send_telegram_message(chat_id: int, text: str, include_owner_buttons: bool = False) -> None:
    token = get_env("TELEGRAM_BOT_TOKEN")
    api_url = urljoin(f"https://api.telegram.org/bot{token}/", "sendMessage")
    payload = {
        "chat_id": str(chat_id),
        "text": text,
    }
    if include_owner_buttons:
        payload["reply_markup"] = json.dumps(
            {
                "inline_keyboard": [
                    [{"text": f"Owner: {OWNER_NAME}", "url": INSTAGRAM_URL}],
                    [{"text": "Instagram: @priyanshuxraj", "url": INSTAGRAM_URL}],
                ]
            }
        )
    response = requests.post(api_url, data=payload, timeout=30)
    response.raise_for_status()


def command_guide() -> str:
    return (
        f"Hello! I am {OWNER_NAME}'s NEET result bot.\n\n"
        "Useful commands:\n"
        "/start - Show welcome message and commands\n"
        "help - Show how to use this bot\n"
        "result live or not - Check whether the official NEET result is live\n"
        "check my result - Get help for the official result page\n"
        "who created this bot - Show creator details\n\n"
        "What I can do:\n"
        "1. Tell you whether NEET result is officially live\n"
        "2. Point you to the official NTA NEET portal\n"
        "3. Help explain the result page after you open it\n\n"
        f"{AI_DISCLAIMER}"
    )


def openai_client() -> OpenAI:
    return OpenAI(api_key=get_env("OPENAI_API_KEY"))


def ask_openai(chat_id: int, user_text: str, context_block: str) -> str:
    client = openai_client()
    model = get_env("OPENAI_MODEL", "gpt-4o-mini")
    previous_response_id = CHAT_RESPONSE_IDS.get(chat_id)
    input_text = (
        f"Live context for this reply:\n{context_block}\n\n"
        f"User message:\n{user_text}\n\n"
        "Always stay grounded in the live context above.\n"
        f"Add this disclaimer only when discussing actual result reliability:\n{AI_DISCLAIMER}"
    )

    kwargs = {
        "model": model,
        "instructions": SYSTEM_PROMPT,
        "input": input_text,
    }
    if previous_response_id:
        kwargs["previous_response_id"] = previous_response_id

    response = client.responses.create(**kwargs)
    CHAT_RESPONSE_IDS[chat_id] = response.id
    return response.output_text.strip()


def creator_requested(text: str) -> bool:
    lowered = normalize_text(text)
    return any(
        phrase in lowered
        for phrase in (
            "who created this bot",
            "who made this bot",
            "creator",
            "owner",
            "developer",
        )
    )


def start_lookup_if_possible(chat_id: int) -> tuple[str, bool]:
    context = (
        f"official_result_live={neet_result_live()}\n"
        f"official_result_entry_live={result_entry_live()}\n"
        f"official_site={NEET_URL}\n"
        f"exam_name=NEET\n"
        f"exam_year={exam_year()}\n"
        "User asked to check their exact result. Tell them this bot is currently configured mainly for live-status checking, "
        "and direct candidate-login result retrieval is not wired yet. Guide them to the official site and offer help reading the result page."
    )
    return ask_openai(chat_id, "check my result", context), False


def build_context_for_general_message(text: str) -> str:
    normalized = normalize_text(text)
    return (
        f"official_result_live={neet_result_live()}\n"
        f"official_result_entry_live={result_entry_live()}\n"
        f"official_site={NEET_URL}\n"
        f"creator_name={OWNER_NAME}\n"
        f"exam_name=NEET\n"
        f"exam_year={exam_year()}\n"
        f"homepage_summary={homepage_summary()}\n"
        f"user_message_normalized={normalized}"
    )


def run_alert_check() -> dict:
    state = load_state()
    live = neet_result_live()

    if live and not state.get("already_alerted", False):
        chat_id = int(get_env("TELEGRAM_CHAT_ID"))
        send_telegram_message(
            chat_id,
            f"NEET result appears to be live now on the official site: {NEET_URL}",
        )
        state["already_alerted"] = True
        save_state(state)
        return {"ok": True, "alert_sent": True, "live": True}

    if not live and state.get("already_alerted", False):
        state["already_alerted"] = False
        save_state(state)

    return {"ok": True, "alert_sent": False, "live": live}


@app.get("/")
def healthcheck():
    return jsonify({"ok": True, "service": "neet-telegram-bot"})


@app.post("/telegram")
def telegram_webhook():
    update = request.get_json(silent=True) or {}
    message = update.get("message") or {}
    chat = message.get("chat") or {}
    text = message.get("text")
    chat_id = chat.get("id")

    if not text or not chat_id:
        return jsonify({"ok": True})

    normalized = normalize_text(text)
    include_owner_buttons = creator_requested(text)

    try:
        if normalized in {"/start", "start", "help", "/help", "commands", "menu"}:
            reply = command_guide()
        elif any(
            phrase in normalized
            for phrase in (
                "check result",
                "my result",
                "check my result",
                "result check",
                "check my marks",
                "get my result",
            )
        ):
            reply, include_owner_buttons = start_lookup_if_possible(chat_id)
        else:
            reply = ask_openai(chat_id, text, build_context_for_general_message(text))
    except Exception as exc:
        print(f"Telegram AI reply failed: {type(exc).__name__}: {exc}", flush=True)
        if normalized in {"help", "/help", "/start", "start"}:
            reply = command_guide()
        elif "result" in normalized or "live" in normalized or "neet" in normalized:
            reply = (
                f"I could not use the AI reply right now, but I checked the official site.\n"
                f"{'The result appears live.' if neet_result_live() else 'The result is not live yet.'}\n"
                f"Official site: {NEET_URL}"
            )
        else:
            reply = (
                "I could not use the AI reply right now. Please try again in a moment, "
                "or ask: result live or not"
            )

    send_telegram_message(chat_id, reply, include_owner_buttons=include_owner_buttons)
    return jsonify({"ok": True})


@app.get("/check")
def scheduled_check():
    secret = request.args.get("key", "")
    expected = get_env("CRON_SECRET")
    if secret != expected:
        return jsonify({"ok": False, "error": "unauthorized"}), 403
    return jsonify(run_alert_check())


if __name__ == "__main__":
    port = int(os.environ.get("PORT", "10000"))
    app.run(host="0.0.0.0", port=port)
